from datetime  import datetime

WIDTH = 320
HEIGHT = 240
CP_WIDTH = 608
CP_HEIGHT = 608
CHANNEL = 1
EPOCHS = 20
MAX_MEMORY = 512
MODEL_PATH = 'trained_models/'
MODEL_NAME = 'OBSTACLESAVOIDINGROBOT' + datetime.now().strftime('%Y%m%d%H%M')+'.h5'
MP_MN = MODEL_PATH + MODEL_NAME
MINIMUM_DISTANCE = 20
THRESHOLD = 8
TRAIN_TIME =  300
MAXIMUM_MODEL_NUMBER  = 7
